# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangcxx_compilerclangxx
    - CONFIG=osx_c_compilertoolchain_ccxx_compilertoolchain_cxx

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "37qyacd+sQ+/0T+/n9+63Cat4Z0yo6WTDAHHRxZtM17U1Fjp6J1CxFzE/zF4HDQsBG0lonLmspyQK6Ih2Cj3mowEMmglUJStkSn0zjMSmMJmpwQt0DXFyCguYwrWcGcKm6P2SNDvRnhKniSnWW1zJ6Lc1qpvptT4mHFl/mvRwQo9cAtrokIxWcvjplbm00x04VX+U3eXk+Ppb/wcHA8nt5DDWVUW59J98F7J8ZJKISDl1q4vYxCDLgQ5QOQe4dt5En281BpSFNfSCaNoUambYb/WWMFfbIcpilzX1CDaFoe4en0FfVeA9cD/+0epW/vpb6aTEJQW2QteUxe8emGRCUfweiZMWfQZe7hiHt1TJ/KPX6fulNCYTxRkiOeWRtKA5tDYQ+2dKztCm0yt+i1xehOJwueRThXOs7MsvGcE1QUF34vO8Gad1C+vQKp+CuQnrl1G+9BZGlSZoIj4NTyYKnVAsea6DjjqL8JT6tjtxsn14gr4QaoNrBMax5v89Vu3WT5oM0lGzEMdgn6vkQV5jxurMpgME02K2ii62PMo2Ztmh2wcfNxfe4DMZ2ypZKyYjSK//69/YnYrc8xBig4PS19jWvFvJ5Yan02wpA7uPmTUBLxaPLZY4xCYk43KzwyYOqI/1Rm0nH9O2fHRpw4JwuoplhpBIYZkOYtft1YP82c="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml