travis:
  secure:
    BINSTAR_TOKEN: Kz2sZOLF3JlVxhHCCgm8j9a7ofUa2/wNu9MBb3oz2ZP+DmivV3fLXx3JuAb2Q4UkK4cloYlorNtIDQgHJGUI+Qx6Kx96e/zXVEWfAxoMlefBFnzEZm9Dzo/FcWDw2a83ji+Akw5N7r5eEZQGhbuYsNCa3k+MJvEUIz6CZBUO+rW2bqTEAusayGLvr2pZkikriPdl3MVCu914KWIpuZdJgx0iA+w9utR6FazxFSN7KPeVEGYASEOKL7wQCpdfa+jwbWReul59iNjTHBlx7FFINnBGyK7dIORDhlM9H9iw9gPbfCBe/UgyFbHXaI01w4BKTwwp1YvR72htxE1pnrvrD6SDJmShgOOmpSnZ6wMbwoelRgi+iQjjOSuOLudZR2iwXWWK0xenYPQ9LjDFeUzgQCDFnQBZNrqN/SUUNBk59q4/+bwmURAGsn4D3dhWyMxNRj2zBCXJTshbTVO3dysW3vCyeokJpz76t70wSwOJ2miuQ/44kSyvJ8lpZ+sXtKPMwmg6WznT2w0Ydasy/cE1PS9QCB4Td/iOiTUhgrQsxnQ9+DkmnfCBThr93fSWwh+kqeMopqOdm+SdAIUWD1SKM80PEl4a/k58tZ+zNq02Jujfc0d1y385j6LjIMaYl7EejfXKfEQN//PKifVPQlKxCRgvBEtPhE8PI5DNbCigoE8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
