travis:
  secure:
    BINSTAR_TOKEN: ZBkTXZrk7B6IxJt7gpt7ghEUgkoOVvZ/fFwQb4g16xA4dvYpd1YYvLfdk9C+7VC6hFmITz2HilnJ+jLlM8Bj0tYsDFIHjCeKbK7stJZhmh0LSt3CI1s2yVr6pduHhJNwyGuSX8yRAo5v0utT303S6b7II2dfFCe75Sw4GynuyrD/4R5yB8vTykHz/SV8kXBte4jCaBD8Hn6++f1bo5myqobrc1VTiNxlyf84lGE5Gn4C5DjNXoye5ic/97BeWQ9n6xz4ic4tKlZRrwaKb3xwrlwr9X9/MAYyMRYzpWGeJOfJy4iefKqhLnoerSER+hnOLBfOBvaYXp6w0PmZR1IPSyaUzK/eybRbJHVsJIGtFb8qaahHTTuYJxkP4EywY0gJs2rEn7LtAXYZh/Zj6rogjyDXOkdDZzJZfLBqA3YJYzIIwTibjk1zrUqrv/un7+Qs3wHqp8rcgMSkMnUGVT/ATK5SubJ1WHWejOvUTcfOJo4MMI/8Dz5Ds9HIRvoq6GrtxPKFIcQoivkwn2zt2/wQCXxmA3juKgHAbtNE89sQbq7ULalUbB7Lkzl7W54DLyK+uyoOt8YsptC3IXNkz2Kn8M8Ownpq3WhejfhdY8vd3GX66w/xrk49AE5T4h8+4uSqYaX1aoZ2BZXsFsMe77moGoTKWynRjz58oziQVesT4wM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
