travis:
  secure:
    BINSTAR_TOKEN: 37qyacd+sQ+/0T+/n9+63Cat4Z0yo6WTDAHHRxZtM17U1Fjp6J1CxFzE/zF4HDQsBG0lonLmspyQK6Ih2Cj3mowEMmglUJStkSn0zjMSmMJmpwQt0DXFyCguYwrWcGcKm6P2SNDvRnhKniSnWW1zJ6Lc1qpvptT4mHFl/mvRwQo9cAtrokIxWcvjplbm00x04VX+U3eXk+Ppb/wcHA8nt5DDWVUW59J98F7J8ZJKISDl1q4vYxCDLgQ5QOQe4dt5En281BpSFNfSCaNoUambYb/WWMFfbIcpilzX1CDaFoe4en0FfVeA9cD/+0epW/vpb6aTEJQW2QteUxe8emGRCUfweiZMWfQZe7hiHt1TJ/KPX6fulNCYTxRkiOeWRtKA5tDYQ+2dKztCm0yt+i1xehOJwueRThXOs7MsvGcE1QUF34vO8Gad1C+vQKp+CuQnrl1G+9BZGlSZoIj4NTyYKnVAsea6DjjqL8JT6tjtxsn14gr4QaoNrBMax5v89Vu3WT5oM0lGzEMdgn6vkQV5jxurMpgME02K2ii62PMo2Ztmh2wcfNxfe4DMZ2ypZKyYjSK//69/YnYrc8xBig4PS19jWvFvJ5Yan02wpA7uPmTUBLxaPLZY4xCYk43KzwyYOqI/1Rm0nH9O2fHRpw4JwuoplhpBIYZkOYtft1YP82c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
